### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by zz-zik** [botvyns/sarcasm_detection_ukr#1]
Hello author, after having installed datasets and no errors were reported during the installation, but the above error occurs when running coda, looking forward to getting your reply.

**Comment by botvyns** [comment]
Hi there! It works fine when I run code on google colab notebook. I'm not sure what is the issue, but take a look at [link](https://discuss.huggingface.co/t/modulenotfounderror-no-module-named-datasets/21996). Hope it will be helpful

**Comment by zz-zik** [comment]
Thank you very much for your reply, which with your help allowed me to find the cause of the problem.

**Comment by botvyns** [comment]
Happy to help!
